#!/usr/bin/env node

var fs = require('fs'),
blessed = require('blessed');
var screen = blessed.screen();

fs.readFile('./amazonAscii', function(err, data){

	var box = blessed.box({
        top: 'center',
        left: 'center',
        style: {
            bg: 'black',
            fg: 'purple'
        },
        width: 31,
        height: 20,
        content: String(data)
    });

	screen.append(box);
	screen.render();
});

var background = blessed.box({
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    style: {
        bg: 'black'
    }
});

screen.append(background);

// Quit on Escape, q, or Control-C.
screen.key(['escape', 'q', 'C-c'], function(ch, key) {
  return process.exit(0);
});